//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHARE_REST_API.JSON_Object
{
    using System;
    using System.Collections.Generic;

    public class Request
    {
        public Request(){ status = "Pending"; }
        public int RequestID { get; set; }
        public int SenderID { get; set; }
        public int DriverID { get; set; }
        public string status { get; set; }
    }

    public class Rating
    {
        public int RateID { get; set; }
        public int rating1 { get; set; }
        public int MemberID { get; set; }
    }

    public class Trip
    {                
        public string origin { get; set; }
        public string destination { get; set; }
        public string originLatLng { get; set; }
        public string destinationLatLng { get; set; }
        public string arriveTime { get; set; }
        public string femaleOnly { get; set; }
        public double cost { get; set; }
        public int distance { get; set; }
        public string days { get; set; }
        public int duration { get; set; }
        public string costStr { get; set; }
        public string durationStr { get; set; }
        public string distanceStr { get; set; }
    }

    public class TripPassenger : Trip
    {
        public TripPassenger() { }
        public TripPassenger(Trip t)
        {
            this.origin = t.origin;
            this.destination = t.destination;
            this.originLatLng = t.originLatLng;
            this.destinationLatLng = t.destinationLatLng;
            this.arriveTime = t.arriveTime;
            this.femaleOnly = t.femaleOnly;
            this.cost = t.cost;
            this.distance = t.distance;
            this.days = t.days;
            this.duration = t.duration;
            this.costStr = t.costStr;
            this.durationStr = t.durationStr;
            this.distanceStr = t.distanceStr;
            TripDriverID = null;
        }

        public int TripPassengerID { get; set; }
        public int PassengerID { get; set; }
        public int? TripDriverID { get; set; }                
    }

    public class TripDriver : Trip
    {
        public TripDriver() { }

        public TripDriver(Trip t)
        {
            this.origin = t.origin;
            this.destination = t.destination;
            this.originLatLng = t.originLatLng;
            this.destinationLatLng = t.destinationLatLng;
            this.arriveTime = t.arriveTime;
            this.femaleOnly = t.femaleOnly;
            this.cost = t.cost;
            this.distance = t.distance;
            this.days = t.days;
            this.duration = t.duration;
            this.costStr = t.costStr;
            this.durationStr = t.durationStr;
            this.distanceStr = t.distanceStr;
        }
        public int TripDriverID { get; set; }
        public int DriverID { get; set; }
        public string PassengerIDs { get; set; }
        public int availableSeat { get; set; }
    }   

    public class CarModel
    {
        public List<object> Vehicles { get; set; }
        public int CarModelID { get; set; }
        public string make { get; set; }
        public string model { get; set; }
    }

    public class Vehicle
    {        
        public int VehicleID { get; set; }
        public int MemberID { get; set; }        
        public int availableSeat { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string plateNo { get; set; }        
    }

    public class Member
    {        
        public int MemberID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string phoneno { get; set; }
        public string type { get; set; }
    }

    public class Route
    {
        public int RouteID { get; set; }
        public int TripID { get; set; }
        public string PassengerTripIDs { get; set; }
    }

    public class Rating2
    {
        public int RateID { get; set; }
        public int rating1 { get; set; }
        public int MemberID { get; set; }
    }

    public class CarModel2
    {
        public List<object> Vehicles { get; set; }
        public int CarModelID { get; set; }
        public string make { get; set; }
        public string model { get; set; }
    }

    public class Vehicle2
    {
        public CarModel2 CarModel { get; set; }
        public int VehicleID { get; set; }
        public int MemberID { get; set; }
        public int CarModelID { get; set; }
        public int availableSeat { get; set; }
    }

    public class Member3
    {
        public List<Rating2> Ratings { get; set; }
        public List<object> Requests { get; set; }
        public List<object> Requests1 { get; set; }
        public List<object> Trips { get; set; }
        public List<Vehicle2> Vehicles { get; set; }
        public int MemberID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string phoneno { get; set; }
        public string type { get; set; }
    }

    public class Trip2
    {
        public List<object> Routes { get; set; }
        public List<object> Requests { get; set; }
        public List<object> Requests1 { get; set; }
        public int TripID { get; set; }
        public int MemberID { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public string arriveTime { get; set; }
        public string femaleOnly { get; set; }
        public int cost { get; set; }
        public int distance { get; set; }
        public string days { get; set; }
    }

    public class Member12
    {
        public List<object> Ratings { get; set; }
        public List<object> Requests { get; set; }
        public List<object> Requests1 { get; set; }
        public List<Trip2> Trips { get; set; }
        public List<object> Vehicles { get; set; }
        public int MemberID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string phoneno { get; set; }
        public string type { get; set; }
    }

    public class Member4
    {
        public List<object> Ratings { get; set; }
        public List<object> Requests { get; set; }
        public List<object> Requests1 { get; set; }
        public List<object> Trips { get; set; }
        public List<object> Vehicles { get; set; }
        public int MemberID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string phoneno { get; set; }
        public string type { get; set; }
    }

    public class Trip12
    {
        public Member4 Member { get; set; }
        public List<object> Routes { get; set; }
        public List<object> Requests { get; set; }
        public List<object> Requests1 { get; set; }
        public int TripID { get; set; }
        public int MemberID { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public string arriveTime { get; set; }
        public string femaleOnly { get; set; }
        public int cost { get; set; }
        public int distance { get; set; }
        public string days { get; set; }
    }

    public class Request2
    {
        public Member3 Member { get; set; }
        public Member12 Member1 { get; set; }
        public Trip12 Trip1 { get; set; }
        public int RequestID { get; set; }
        public int SenderID { get; set; }
        public int DriverID { get; set; }
        public string status { get; set; }
    }

    public class Trips
    {
        public Member Member { get; set; }
        public List<Route> Routes { get; set; }
        public List<Request2> Requests { get; set; }
        public List<object> Requests1 { get; set; }
        public int TripID { get; set; }
        public int MemberID { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public string arriveTime { get; set; }
        public string femaleOnly { get; set; }
        public double cost { get; set; }
        public int distance { get; set; }
        public string days { get; set; }
        public int duration { get; set; }
    }            
}
