//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHARE_REST_API.JSON_Object
{
    using System;
    using System.Collections.Generic;

    public class Request
    {        
        public Request() { status = "Pending"; }
        public int RequestID { get; set; }
        public int SenderID { get; set; }
        public int DriverID { get; set; }
        public string status { get; set; }
        public TripDriver TripDriver { get; set; }
        public TripPassenger TripPassenger { get; set; }
    }

    public class Rating
    {        
        public Rating(int rater, int member, int rate, string comment)
        {
            RaterID= rater ;
            MemberID = member;
            this.rate = rate;
            this.comment = comment;
        }
        public int RateID { get; set; }
        public int RaterID { get; set; }
        public int MemberID { get; set; }
        public int rate { get; set; }
        public string comment { get; set; }
        
    }

    public class Trip
    {
        public Member Member { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public string originLatLng { get; set; }
        public string destinationLatLng { get; set; }
        public string arriveTime { get; set; }
        public string femaleOnly { get; set; }
        public double cost { get; set; }
        public double distance { get; set; }
        public string days { get; set; }
        public int duration { get; set; }
        public string costStr { get; set; }
        public string durationStr { get; set; }
        public string distanceStr { get; set; }
    }

    public class TripPassenger : Trip
    {
        public TripPassenger() { }
        public TripPassenger(TripDetails t)
        {
            this.Member = t.Member;
            this.origin = t.origin;
            this.destination = t.destination;
            this.originLatLng = t.originLatLng;
            this.destinationLatLng = t.destinationLatLng;
            this.arriveTime = t.arriveTime;
            this.femaleOnly = t.femaleOnly;
            this.cost = t.cost;
            this.distance = t.distance;
            this.days = t.days;
            this.duration = t.duration;
            this.costStr = t.costStr;
            this.durationStr = t.durationStr;
            this.distanceStr = t.distanceStr;
            TripDriverID = t.TripDriverID;
            PassengerID = t.PassengerID;
            TripPassengerID = t.TripPassengerID;
        }
        public TripPassenger(Trip t)
        {
            this.origin = t.origin;
            this.destination = t.destination;
            this.originLatLng = t.originLatLng;
            this.destinationLatLng = t.destinationLatLng;
            this.arriveTime = t.arriveTime;
            this.femaleOnly = t.femaleOnly;
            this.cost = t.cost;
            this.distance = t.distance;
            this.days = t.days;
            this.duration = t.duration;
            this.costStr = t.costStr;
            this.durationStr = t.durationStr;
            this.distanceStr = t.distanceStr;
            TripDriverID = null;
        }

        public int TripPassengerID { get; set; }
        public int PassengerID { get; set; }
        public int? TripDriverID { get; set; }
    }

    public class TripDriver : Trip
    {
        public TripDriver() { }

        public TripDriver(TripDetails t)
        {
            this.Member = t.Member;
            this.origin = t.origin;
            this.destination = t.destination;
            this.originLatLng = t.originLatLng;
            this.destinationLatLng = t.destinationLatLng;
            this.arriveTime = t.arriveTime;
            this.femaleOnly = t.femaleOnly;
            this.cost = t.cost;
            this.distance = t.distance;
            this.days = t.days;
            this.duration = t.duration;
            this.costStr = t.costStr;
            this.durationStr = t.durationStr;
            this.distanceStr = t.distanceStr;
            TripDriverID = (int)t.TripDriverID;
            DriverID = t.DriverID;
            PassengerIDs = t.PassengerIDs;
            availableSeat = t.availableSeat;
        } 
        public TripDriver(Trip t)
        {
            this.origin = t.origin;
            this.destination = t.destination;
            this.originLatLng = t.originLatLng;
            this.destinationLatLng = t.destinationLatLng;
            this.arriveTime = t.arriveTime;
            this.femaleOnly = t.femaleOnly;
            this.cost = t.cost;
            this.distance = t.distance;
            this.days = t.days;
            this.duration = t.duration;
            this.costStr = t.costStr;
            this.durationStr = t.durationStr;
            this.distanceStr = t.distanceStr;
        }
        public int TripDriverID { get; set; }
        public int DriverID { get; set; }
        public string PassengerIDs { get; set; }
        public int availableSeat { get; set; }
    }   

    public class CarModel
    {
        public List<object> Vehicles { get; set; }
        public int CarModelID { get; set; }
        public string make { get; set; }
        public string model { get; set; }
    }

    public class Vehicle
    {        
        public int VehicleID { get; set; }
        public int MemberID { get; set; }                
        public string make { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string plateNo { get; set; }        
    }

    public class Member
    {
        public List<Rating> Ratings { get; set; }
        public List<Vehicle> Vehicles { get; set; }
        public int MemberID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string phoneno { get; set; }
        public string type { get; set; }
        public double rate { get; set; }
    }

    public class Route
    {
        public int TripID { get; set; }
        public int RouteID { get; set; }
        public string PassengerTripIDs { get; set; }
    }

    
}
